services:
  valkey:
    image: valkey/valkey:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'valkey_data:/valkey/data'

volumes:
  valkey_data:
    driver: local
